#!/bin/bash
# Quick reference for Erlebrain → Pixhawk 2.4.8 migration

echo "=========================================="
echo "PIXHAWK 2.4.8 MIGRATION - ALL RESOURCES"
echo "=========================================="
echo ""
echo "📚 DOCUMENTATION CREATED:"
echo ""
echo "1. PIXHAWK_START_HERE.md (← READ THIS FIRST!)"
echo "   └─ Overview, decision tree, quick reference"
echo ""
echo "2. PIXHAWK_QUICK_START.md"
echo "   └─ Fast path to first flight (2-3 days)"
echo ""
echo "3. PIXHAWK_MIGRATION_INDEX.md"
echo "   └─ Navigation guide for all resources"
echo ""
echo "4. PIXHAWK_2_4_8_MIGRATION_GUIDE.md"
echo "   └─ Complete technical migration guide (6 phases)"
echo ""
echo "5. PIXHAWK_MIGRATION_CHECKLIST.md"
echo "   └─ Detailed step-by-step verification"
echo ""
echo "6. PIXHAWK_AIC_COMPILATION_GUIDE.md"
echo "   └─ Custom firmware compilation (advanced)"
echo ""
echo "7. config/flight_params_pixhawk.yaml"
echo "   └─ Configuration template (COPY & EDIT THIS!)"
echo ""
echo "=========================================="
echo "🎯 RECOMMENDED NEXT STEPS:"
echo "=========================================="
echo ""
echo "Option A: FASTEST PATH (impatient)"
echo "  1. cat PIXHAWK_START_HERE.md"
echo "  2. cat PIXHAWK_QUICK_START.md"
echo "  3. Follow Day 1-4"
echo ""
echo "Option B: THOROUGH PATH (want to understand)"
echo "  1. cat PIXHAWK_START_HERE.md"
echo "  2. cat PIXHAWK_2_4_8_MIGRATION_GUIDE.md"
echo "  3. Use PIXHAWK_MIGRATION_CHECKLIST.md as you work"
echo ""
echo "Option C: DETAILED CHECKLIST PATH (like checkboxes)"
echo "  1. cat PIXHAWK_MIGRATION_CHECKLIST.md"
echo "  2. Work through 6 phases with checkmarks"
echo ""
echo "=========================================="
echo "⚠️  CRITICAL CHANGES:"
echo "=========================================="
echo ""
echo "1. BAUD RATE: 921600 → 115200 (DO THIS FIRST!)"
echo "   File: config/flight_params.yaml"
echo "   Change: connection.baud_rate: 115200"
echo ""
echo "2. CONNECTION STRING: Update for your Pixhawk port"
echo "   macOS: /dev/cu.usbmodem14101 (run: ls /dev/cu.usb*)"
echo "   Linux: /dev/ttyUSB0 (run: ls /dev/ttyUSB*)"
echo ""
echo "3. COMPASS DECLINATION: Your location"
echo "   Find at: www.magnetic-declination.com"
echo ""
echo "=========================================="
echo "✅ QUICK VERIFICATION:"
echo "=========================================="
echo ""
echo "All migration documents:"
ls -lh PIXHAWK*.md config/flight_params_pixhawk.yaml 2>/dev/null | awk '{print "   " $9, "(" $5 ")"}'
echo ""
echo "=========================================="
echo "🚀 START NOW:"
echo ""
echo "   cat PIXHAWK_START_HERE.md"
echo ""
echo "=========================================="
