#!/bin/bash
# Erle-Brain 2 WiFi Connection Guide

echo "=========================================="
echo "Erle-Brain 2 WiFi Connection Guide"
echo "=========================================="
echo ""
echo "Your Erle-Brain is blinking - that's good! ✓"
echo ""
echo "STEP 1: Find the Erle-Brain WiFi Network"
echo "=========================================="
echo ""
echo "Look for one of these WiFi network names (SSID):"
echo "  • erle-brain-2"
echo "  • erle-brain"
echo "  • erlerobot"
echo "  • ErleRobotics"
echo ""
echo "On macOS:"
echo "  1. Click the WiFi icon in menu bar"
echo "  2. Look for networks starting with 'erle' or 'robot'"
echo ""
echo "Common Erle-Brain WiFi default:"
echo "  SSID: erle-brain-2"
echo "  Password: (usually open/no password, or 'holaerle')"
echo ""
echo "----------------------------------------"
echo ""
echo "STEP 2: Connect to Erle-Brain WiFi"
echo "=========================================="
echo ""
echo "Option A - Erle-Brain as Access Point:"
echo "  1. Connect to 'erle-brain-2' WiFi network"
echo "  2. Once connected, try:"
echo "     ssh erle@11.0.0.1"
echo "     OR"
echo "     ssh erle@192.168.7.2"
echo "     Password: holaerle"
echo ""
echo "Option B - Erle-Brain on Your WiFi:"
echo "  If Erle-Brain is already configured to join your network,"
echo "  we need to find its IP address."
echo ""
echo "  Try these commands to find it:"
echo "  1. Check router admin page for connected devices"
echo "  2. Look for 'erle-brain' or device with hostname 'erlerobot'"
echo ""
echo "----------------------------------------"
echo ""
echo "STEP 3: Test Connection"
echo "=========================================="
echo ""
echo "Once you know the IP or hostname, test with:"
echo ""
echo "  ping <IP_ADDRESS>"
echo "  ssh erle@<IP_ADDRESS>"
echo "  Password: holaerle"
echo ""
echo "Common IP addresses to try:"
echo "  • 11.0.0.1      (if connected to Erle-Brain AP)"
echo "  • 192.168.7.2   (if connected via USB/Ethernet)"
echo "  • 192.168.1.x   (if on your home network)"
echo "  • 10.124.95.x   (your current network range)"
echo ""
echo "----------------------------------------"
echo ""
echo "QUICK TEST - Try these now:"
echo "=========================================="
echo ""

# Try common IPs
for IP in 11.0.0.1 192.168.7.2 192.168.1.100 10.124.95.100; do
    echo -n "Testing $IP... "
    if ping -c 1 -W 1 $IP &>/dev/null; then
        echo "✓ Responds!"
        echo "  Try: ssh erle@$IP"
    else
        echo "✗ No response"
    fi
done

echo ""
echo "----------------------------------------"
echo ""
echo "TROUBLESHOOTING:"
echo "=========================================="
echo ""
echo "If nothing works:"
echo ""
echo "1. Restart Erle-Brain (power cycle)"
echo "2. Wait 1-2 minutes for boot up"
echo "3. Check WiFi networks again"
echo "4. Look in System Preferences > Network for new WiFi networks"
echo ""
echo "Need to configure Erle-Brain WiFi?"
echo "  - Connect via Ethernet first"
echo "  - Or connect via USB (appears as 192.168.7.2)"
echo "  - Then configure WiFi from there"
echo ""
echo "=========================================="
echo ""
echo "What to do next:"
echo "  1. Find the WiFi network name (SSID) from your WiFi menu"
echo "  2. Connect to it"
echo "  3. Note the IP address you get"
echo "  4. SSH to that IP: ssh erle@<IP>"
echo ""
